## Dockerfile to create devel version of CoRR Database

FROM ubuntu:16.04
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get -y update
RUN apt-get install -y sudo
RUN apt-get install -y apt-utils
RUN apt-get install bzip2
RUN apt-get install -y build-essential
RUN apt-get -y update
RUN apt-get install -y git
RUN apt-get install -y wget
RUN sudo apt-get install -y mongodb

RUN sudo mkdir /data
RUN sudo mkdir /data/db

## Create a user with no sudo password.

RUN useradd -m {{ ansible_ssh_user }}
RUN passwd -d {{ ansible_ssh_user }}
RUN adduser {{ ansible_ssh_user }} sudo
RUN echo '{{ ansible_ssh_user }} ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

USER {{ ansible_ssh_user }}
WORKDIR {{ local_path }}

COPY requirements.yaml {{ local_path }}/requirements.yaml
COPY corr {{ local_path }}/corr
COPY mongodb.conf /etc/mongodb.conf

RUN sudo chown {{ ansible_ssh_user }}:{{ ansible_ssh_user }} {{ local_path }}/corr -R

RUN sudo chown {{ ansible_ssh_user }}:{{ ansible_ssh_user }} {{ local_path }}/requirements.yaml

#RUN git clone -b {{corr_version}} https://github.com/{{ corr_repo }}.git
RUN wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
RUN bash Miniconda-latest-Linux-x86_64.sh -b -p {{ anaconda_path }}
RUN echo 'export PATH="{{ local_path }}/anaconda/bin:$PATH"'>> {{ local_path }}/.bashrc
RUN {{ conda }} update -y conda
RUN {{ conda }} create -y -n {{ corr_env }} python=3.4
RUN {{ conda }} env update -n {{ corr_env }} --file {{ local_path }}/requirements.yaml

RUN sudo chown {{ ansible_ssh_user }}:{{ ansible_ssh_user }} {{ local_path }}/corr -R

WORKDIR {{ local_path }}/corr/corr-db

RUN {{ env_path }}/python setup.py install

EXPOSE {{ mapped_port }}

VOLUME /data/db

#CMD sudo service mongodb start
CMD sudo mongod --bind_ip {{ hostvars['dbhost']['ansible_ssh_host'] }} --port {{hostvars['dbhost']['mapped_port']}}