- name: playbook for docker-compose CoRR
  hosts: all
  connection: local
  gather_facts: no
  vars:
    local_path: "/home/{{ docker_user }}"
    anaconda_path: "{{ local_path }}/{{ anacondadir }}"
    default_corr_path: "{{ corr_location }}/corr"
    conda: "{{ anaconda_path }}/bin/conda"
    env_path: "{{ anaconda_path }}/envs/{{ corr_env }}/bin"
    python: "{{ anaconda_path }}/envs/{{ corr_env }}/bin/python"
  tasks:
    - include: clean.yaml
      tags: [install]

    - include: corr_path.yaml
      tags: [install]

    - include: clone.yaml
      tags: [install]

    - name: Copy src to build
      tags: [install]
      shell: cp -R {{ default_corr_path }} {{ inventory_dir }}/builds

    - name: generate Dockerfile-db file.
      tags: [install]
      when: inventory_hostname in groups['db']
      template: src={{ inventory_dir }}/Dockerfile-db.j2 dest={{ inventory_dir }}/builds/Dockerfile-db

    - name: generate Dockerfile-api file.
      tags: [install]
      when: inventory_hostname in groups['api']
      template: src={{ inventory_dir }}/Dockerfile-api.j2 dest={{ inventory_dir }}/builds/Dockerfile-api

    - name: create api config folder directory
      tags: [install]
      when: inventory_hostname in groups['api']
      file: path={{ inventory_dir }}/builds/corr/corr-api/config state=directory

    - name: copy api default config file
      tags: [install]
      when: inventory_hostname in groups['api']
      template: src={{ inventory_dir }}/virtualbox/config-api.py.j2 dest={{ inventory_dir }}/builds/corr/corr-api/config/default.py

    - name: generate Dockerfile-cloud file.
      tags: [install]
      when: inventory_hostname in groups['cloud']
      template: src={{ inventory_dir }}/Dockerfile-cloud.j2 dest={{ inventory_dir }}/builds/Dockerfile-cloud

    - name: copy admin generation template
      when: inventory_hostname in groups['cloud']
      template: src={{ inventory_dir }}/tmp_admin.json.j2 dest={{ inventory_dir }}/builds/tmp_admin.json
      tags: [install]

    - name: copy admin generation template
      when: inventory_hostname in groups['cloud']
      template: src={{ inventory_dir }}/admin_generation.py.j2 dest={{ inventory_dir }}/builds/corr/corr-cloud/cloud/views/admin_generation.py
      tags: [install]

    - name: create cloud config folder directory
      tags: [install]
      when: inventory_hostname in groups['cloud']
      file: path={{ inventory_dir }}/builds/corr/corr-cloud/config state=directory

    - name: copy cloud default config file
      when: inventory_hostname in groups['cloud']
      template: src={{ inventory_dir }}/virtualbox/config-cloud.py.j2 dest={{ inventory_dir }}/builds/corr/corr-cloud/config/default.py
      tags: [install]

    - name: generate Dockerfile-frontend file.
      tags: [install]
      when: inventory_hostname in groups['frontend']
      template: src={{ inventory_dir }}/Dockerfile-frontend.j2 dest={{ inventory_dir }}/builds/Dockerfile-frontend
      become: true

    - name: create frontend config folder directory
      tags: [install]
      when: inventory_hostname in groups['frontend']
      file: path={{ inventory_dir }}/builds/corr/corr-view/frontend/js/config state=directory

    - name: copy frontend default config file
      tags: [install]
      when: inventory_hostname in groups['frontend']
      template: src={{ inventory_dir }}/virtualbox/config-frontend.js.j2 dest={{ inventory_dir }}/builds/corr/corr-view/frontend/js/config/default.js

    - name: copy frontend custom file
      tags: [install]
      when: inventory_hostname in groups['frontend']
      template: src={{ inventory_dir }}/custom.json.j2 dest={{ inventory_dir }}/builds/corr/corr-view/frontend/xml/custom.json

    - name: copy requirements.
      tags: [install]
      shell: cp requirements.yaml builds

    - name: create ~/s3 directory
      tags: [install]
      when: >
        storage_type == "s3" and
        (inventory_hostname in groups['api'] or
        inventory_hostname in groups['cloud'])
      file: path={{ inventory_dir }}/builds/aws state=directory

    - name: copy s3 config
      tags: [install]
      when: >
        storage_type == "s3" and
        (inventory_hostname in groups['api'] or
        inventory_hostname in groups['cloud'])
      template: src={{ inventory_dir }}/config-s3.j2 dest={{ inventory_dir }}/builds/aws/config

    - name: build the latest db image
      tags: [install]
      when: inventory_hostname in groups['db']
      shell: "docker-compose build corrdb"
      become: true

    - name: build the latest api image
      tags: [install]
      when: inventory_hostname in groups['api']
      shell: "docker-compose build corrapi"
      become: true

    - name: build the latest cloud image
      tags: [install]
      when: inventory_hostname in groups['cloud']
      shell: "docker-compose build corrcloud"
      become: true

    - name: build the latest frontend image
      tags: [install]
      when: inventory_hostname in groups['frontend']
      shell: "docker-compose build corrview"
      become: true

    - include: push.yaml
      tags: [push]

    - include: serve.yaml
      tags: [serve]

    - include: restart.yaml
      tags: [restart]

    - include: scale.yaml
      tags: [scale]

    - include: stop.yaml
      tags: [stop]

    - include: status.yaml
      tags: [status]

    - include: clean.yaml
      tags: [clean]
